version: "3.9"
networks:
  spark-network:
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "P@ssw0rD"
        ACCEPT_EULA: "Y"
    networks:
      - spark-network
  spark-master:
    image: "alexgarciamiravet/spark-master:3.1.1-hadoop3.2"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark-network
  spark-worker:
    image: "alexgarciamiravet/spark-worker:3.1.1-hadoop3.2"
    depends_on:
      - "spark-master"
    ports:
      - "8081:8081"
    networks:
      - spark-network
