version: "3.9"
networks:
  spark-network:
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "P@ssw0rD"
        ACCEPT_EULA: "Y"
    networks:
      - spark-network
